# Non Graded Challenge 7
- Muhammad Fadlil Ismail
- FTDS Batch 10 Phase 0

## Soal
- Carilah turunan dari fungsi berikut:
-               3x + 4y = 5


### Persamaan tersebut diubah ke persamaan fungsi x dan fungsi y
#### Persamaan Fungsi x:
-            y = -0.75x + 1.25
#### Persamaan Fungsi y:
-            x = -4/3y + 5/3

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
#Penyelesaian untuk persamaan fungsi x:
x = np.linspace(-50,50)
y = 1.25 - 0.75*x

dydx = np.gradient(y)
dydx

array([-1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224])

In [4]:
import numpy as np

## Define `x`
x = np.linspace(-50, 50)

## Define the function
y = 1.25 - 0.75 * x

result_gradient_x = np.gradient(y)
result_gradient_x

array([-1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224,
       -1.53061224, -1.53061224, -1.53061224, -1.53061224, -1.53061224])

In [8]:
# Penyelesaian untuk persamaan fungsi y
y = np.linspace(-50,50)
x = -4/3*y + 5/3

dxdy = np.gradient(x)
dxdy

array([-2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844,
       -2.72108844, -2.72108844, -2.72108844, -2.72108844, -2.72108844])