# Non Graded Challenge 4
- Muhammad Fadlil Ismail
- FTDS Batch 10 Phase 0

### Nomor 1
Buatlah Matriks berikut dengan numpy:
[[23,50], [7,12]]
[[57,67], [99,43]]
[[75,21], [57,12]]
[[87,26], [18,84]]

In [1]:
import numpy as np

In [17]:
a = [[23,50], [7,12]]
b = [[57,67], [99,43]]
c = [[75,21], [57,12]]
d = [[87,26], [18,84]]
vect = np.array([a,b,c,d])
vect

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [18]:
vect.shape

(4, 2, 2)

### Nomor 2
Soal:
Hitunglah perkalian matriks dari matriks A dan B

In [23]:
A = np.array([[23,50,19], [7,12,109], [57,67,98]])
B = np.array([17,22,19])

Perkalian matriks A dan B (menggunakan notasi @) adalah sebagai berikut:

In [24]:
A @ B.T

array([1852, 2454, 4305])

### Nomor 3
Hitunglah Determinan, Inverse dan Transpose dari matriks berikut

In [25]:
C = [[23,50,19],
     [7,12,109],
     [57,67,98]]
C = np.array(C)
C

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [26]:
# Determinan
np.linalg.det(C)

131344.0000000002

In [28]:
# Inverse
np.linalg.inv(C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [29]:
# Transpose
C.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])