# **MATRIX**

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A.shape

(3, 2)

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Accessing Matrix**

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][2]

6

In [ ]:
A[1,2]

6

In [ ]:
A[:, -1]

array([3, 6, 9])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## **Operasi Aritmatika**

- penjumlahan
- pengurangan
- pembagian
- perkalian

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([[1,2,0],
              [4,1,3],
              [2,5,0]])
B

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

**penjumlahan**

In [ ]:
A + B

array([[ 2,  4,  3],
       [ 8,  6,  9],
       [ 9, 13,  9]])

In [ ]:
10 + A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

**pengurangan**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A - B

array([[0, 0, 3],
       [0, 4, 3],
       [5, 3, 9]])

In [ ]:
10 - A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

**pembagian**

In [ ]:
B / A

array([[1.        , 1.        , 0.        ],
       [1.        , 0.2       , 0.5       ],
       [0.28571429, 0.625     , 0.        ]])

**perkalian**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# perkalian dengan skalar
A * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# perkalian hadamard product (element-wise multiplication)
A * np.eye(3)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [ ]:
# perkalian matrix
J = np.array([[1, 2, 0],
              [0, 3, 1],
              [1, 0, 0]])

K = np.array([[0, 1],
              [1, 2],
              [0, 1]])


In [ ]:
J

array([[1, 2, 0],
       [0, 3, 1],
       [1, 0, 0]])

In [ ]:
K

array([[0, 1],
       [1, 2],
       [0, 1]])

In [ ]:
J @ K

array([[2, 5],
       [3, 7],
       [0, 1]])

In [ ]:
L = np.array([[3, 1, 7],
              [4, 5, 6]])

K = np.array([[2],
              [1],
              [0]])

In [ ]:
L

array([[3, 1, 7],
       [4, 5, 6]])

In [ ]:
K

array([[2],
       [1],
       [0]])

In [ ]:
H = L @ K
H.shape

(2, 1)

**transpose**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Inverse**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

In [ ]:
inv_B = np.linalg.inv(B)
inv_B

array([[ 5.        ,  0.        , -2.        ],
       [-2.        ,  0.        ,  1.        ],
       [-6.        ,  0.33333333,  2.33333333]])

In [ ]:
B @ inv_B # perkalian matriks dengan inversnya menghasilkan matriks identitas

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 1.0000000e+00]])

In [ ]:
np.linalg.inv(A) # error singular matrix

LinAlgError: ignored

## **Determinan**

In [ ]:
np.linalg.det(B)

-3.000000000000001

In [ ]:
np.linalg.det(A) # matriks dengan determinan 0 tidak memiliki invers

0.0

In [ ]:
# singular matriks - baris merupakan kelipatan dari baris yang lain
C = np.array([[1, 2],
             [3, 6]])

np.linalg.det(C)

0.0

In [ ]:
0.1 + 0.2

0.30000000000000004

In [ ]:
# singular matriks - baris merupakan kombinasi linear dari baris yang lain
D = np.array([[1, 4, 6],
              [2, 0, 1],
              [3, 4, 7]])

np.linalg.inv(D) # error singular matrix

LinAlgError: ignored

## Tensor

In [ ]:
X = np.array([[1, 5, 1, 3],
              [3, 7, 2, 1]])

Y = np.array([[5, 1, 2, 5],
              [5, 1, 0, 0]])

Z = np.array([[0, 6, 1, 0],
              [3, 1, 0, 0]])

In [ ]:
X.shape

(2, 4)

In [ ]:
tensor = np.array([X, Y, Z])
tensor

array([[[1, 5, 1, 3],
        [3, 7, 2, 1]],

       [[5, 1, 2, 5],
        [5, 1, 0, 0]],

       [[0, 6, 1, 0],
        [3, 1, 0, 0]]])

In [ ]:
tensor.shape

(3, 2, 4)

shape = (3, 2, 4); means that this tensor consists of 3 matrices which each has 2 rows and 4 columns.