In [1]:
import numpy as np

In [3]:
tinggi = [1.7, 1.8, 1.9, 1.5, 1.4, 1.65]
berat = [63, 75, 85, 50, 35, 70]

np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

np_tinggi/np_berat

array([0.02698413, 0.024     , 0.02235294, 0.03      , 0.04      ,
       0.02357143])

In [4]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [20]:
#Append Array (sedikit berbeda dgn list)
arr = np.array([1,2,3,4,5])
arr = np.append(arr, [6,7,8,9])
print(arr)

#Delete array, menghapus berdasar indeks
np.delete(arr,3)


[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 5, 6, 7, 8, 9])

In [22]:
print(arr.shape)
print(arr.ndim)

(9,)
1


In [33]:
arr=arr.reshape(-1,1)
print(arr)
print(arr.shape)
print(arr.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)
2


In [30]:
# 2D array
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8


In [32]:
coba = np.array([[[1,1,1,1]]])
print(coba)
print(coba.size)
print(coba.shape)
coba.ndim

[[[1 1 1 1]]]
4
(1, 1, 4)


3

In [38]:
arr3 = np.arange(7)
print(arr3.shape)
arr3 = arr3[np.newaxis,:] # hasil sama dengan arr3[np.newaxis]
print(arr3)
print(arr3.shape)

(7,)
[[0 1 2 3 4 5 6]]
(1, 7)


In [37]:
arr4 = np.arange(7)
print(arr4.shape)
arr4 = arr4[:, np.newaxis]
print(arr4)
print(arr4.shape)

(7,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(7, 1)


In [39]:
a = np.arange(9)

In [40]:
a1 = np.expand_dims(a, axis=0)
print(a1)
print(a1.shape)

[[0 1 2 3 4 5 6 7 8]]
(1, 9)


In [42]:
a2 = np.expand_dims(a, axis=1)
print(a2)
print(a2.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


In [ ]:
# axis=0 baris, axis=1 kolom

In [47]:
arr_a = np.array([1,2,3,4,5,6])
print(arr_a[2:6])

[3 4 5 6]


In [49]:
coba2 = np.array([[1,2,3,4], [5,6,7,8]])
print(coba2[coba2>3])

[4 5 6 7 8]


In [53]:
b1 = np.array([[1,1],
                [2,2]])

b2 = np.array([[3,3],
                [4,4]])

print(np.vstack((b1,b2)))
print(np.hstack((b1,b2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
